backend:
  name: git-gateway
  branch: main # change to master if your main branch is master

media_folder: "images/uploads" # where uploaded images will be stored
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"  # create this folder in your project next
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
